# This file was generated by GoReleaser. DO NOT EDIT.
cask "router-hosts" do
  version "0.10.1"

  on_macos do
    on_intel do
      sha256 "fd06c78dc430a70807c8d2d36104b075cd9128a54ef52009a3510158560c39a7"
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8a5e39e63843343b9243f8fee244da5881cb20ed80b2ab4337d4cb4cc9872048"
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a53ff8ed6fa9607a5768c32ee4efad7d99286c4da5c8f86491ed212d0b19a428"
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd10c56492e52ee224d4ae9b67da1b0fb2440e837934f111b5f35c8f7f74e739"
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_linux_arm64.tar.gz"
    end
  end

  name "router-hosts"
  desc "CLI for managing DNS host entries via gRPC over mTLS"
  homepage "https://github.com/fzymgc-house/router-hosts"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "router-hosts"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/router-hosts"]
    end
  end

  # No zap stanza required

end
