# This file was generated by GoReleaser. DO NOT EDIT.
cask "router-hosts" do
  name "router-hosts"
  desc "CLI for managing DNS host entries via gRPC over mTLS"
  homepage "https://github.com/fzymgc-house/router-hosts"
  version "0.9.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "router-hosts"

  on_macos do
    on_intel do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_darwin_amd64.tar.gz"
      sha256 "944975443eeec764f4ded5d449cc646156d19bc1657cfa1dbcf5b27986272679"
    end
    on_arm do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_darwin_arm64.tar.gz"
      sha256 "379e120b2eb34b80005f071385dc7e8a72b09a0679bcd2240ca7815df1fb27eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_linux_amd64.tar.gz"
      sha256 "8b96380eda354af6bfec9785a317ca273af9bf433de800b7352c2f50fab6eb8f"
    end
    on_arm do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_linux_arm64.tar.gz"
      sha256 "4ce96162059348ff661c80945c741d7b31b00d002368f4de2dd62a6e3f8ff952"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/router-hosts"]
    end
  end

  # No zap stanza required
end
