# This file was generated by GoReleaser. DO NOT EDIT.
cask "router-hosts" do
  name "router-hosts"
  desc "CLI for managing DNS host entries via gRPC over mTLS"
  homepage "https://github.com/fzymgc-house/router-hosts"
  version "0.9.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "router-hosts"

  on_macos do
    on_intel do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_darwin_amd64.tar.gz"
      sha256 "e55bde1c838e8fd00fea155ee94bda482518ab77e9ff231c3ed7630bd52644ba"
    end
    on_arm do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_darwin_arm64.tar.gz"
      sha256 "9115ab3e57b84973ff1c44259aedecd2f45b246ee0c3c200dc7e2828cb7b938c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_linux_amd64.tar.gz"
      sha256 "8d6847345cb49e2df35de6700bfe5e6eb083dc13050bb8d6d5b0efae96bbb92c"
    end
    on_arm do
      url "https://github.com/fzymgc-house/router-hosts/releases/download/v#{version}/router-hosts_linux_arm64.tar.gz"
      sha256 "a4a5f83883bb9a8afaa7cfb51c60fffffe84477ef290dc21194f8dbccf0e3601"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/router-hosts"]
    end
  end

  # No zap stanza required
end
